# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'data_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_stream.proto\x12\x06stream\"\x8a\x01\n\x0fTHStreamRequest\x12\r\n\x05seqNo\x18\x01 \x01(\t\x12\x0f\n\x07rgbData\x18\x02 \x01(\x0c\x12\x11\n\tpointData\x18\x03 \x01(\x0c\x12\x10\n\x08\x66\x61\x63\x65\x44\x61ta\x18\x04 \x01(\x0c\x12\x10\n\x08limbData\x18\x05 \x01(\x0c\x12\x0f\n\x07\x65xtData\x18\x06 \x01(\x0c\x12\x0f\n\x07\x65xtDesc\x18\x07 \x01(\t\"3\n\x10THStreamResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\x12\x0e\n\x06retMsg\x18\x02 \x01(\t2_\n\x0fTHStreamService\x12L\n\x13\x42idirectionalStream\x12\x17.stream.THStreamRequest\x1a\x18.stream.THStreamResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THSTREAMREQUEST']._serialized_start=30
  _globals['_THSTREAMREQUEST']._serialized_end=168
  _globals['_THSTREAMRESPONSE']._serialized_start=170
  _globals['_THSTREAMRESPONSE']._serialized_end=221
  _globals['_THSTREAMSERVICE']._serialized_start=223
  _globals['_THSTREAMSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
