# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_stream_pb2 as data__stream__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class THStreamServiceStub(object):
    """定义服务StreamService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BidirectionalStream = channel.stream_stream(
                '/stream.THStreamService/BidirectionalStream',
                request_serializer=data__stream__pb2.THStreamRequest.SerializeToString,
                response_deserializer=data__stream__pb2.THStreamResponse.FromString,
                _registered_method=True)


class THStreamServiceServicer(object):
    """定义服务StreamService
    """

    def BidirectionalStream(self, request_iterator, context):
        """双向流式RPC，客户端和服务端可以同时发送和接收消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_THStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=data__stream__pb2.THStreamRequest.FromString,
                    response_serializer=data__stream__pb2.THStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.THStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream.THStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class THStreamService(object):
    """定义服务StreamService
    """

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/stream.THStreamService/BidirectionalStream',
            data__stream__pb2.THStreamRequest.SerializeToString,
            data__stream__pb2.THStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
